# Generated by Django 5.2.4 on 2026-04-08 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulseTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_before', models.FloatField()),
                ('v_after', models.FloatField()),
                ('current_ma', models.FloatField()),
                ('temperature_c', models.FloatField()),
                ('internal_resistance', models.FloatField(blank=True, null=True)),
                ('calculated_soh', models.FloatField(blank=True, null=True)),
                ('calculated_soc', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_tests', to='monitoring.battery')),
            ],
        ),
    ]
