# Generated by Django 5.2.4 on 2026-04-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_pulsetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='energy_wh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='max_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='period_seconds',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='reading',
            name='power_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='samples_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reading',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
