# Generated by Django 5.2.4 on 2026-04-12 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_reading_energy_wh_alter_reading_max_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
