# Generated by Django 5.2.4 on 2026-05-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_activesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='cycle_count',
            field=models.FloatField(default=0.0),
        ),
    ]
